### PR TITLE
Add phpcbf, phpcs, php-cs-fixer

### PR DESCRIPTION
**Pull request by p1u3o**
Adds phpcbf, phpcs and php-cs-fixer.

This means the relevant VSCode plugins just "work".

### CODE REVIEW

**Comment by Lctrs** [comment]
Hm. I'm leaning towards a :-1: on this one. Can't users just install this through composer (either globally or locally) ?

**Comment by p1u3o** [comment]
> Hm. I'm leaning towards a -1 on this one. Can't users just install this through composer (either globally or locally) ?

Kinda. Global doesn't work right now as it will install into `/var/home/pluto/.var/app/com.visualstudio.code/config/composer/vendor/bin` outside of the PATH. 

Would a better idea be to add `/var/config/composer/vendor/bin` to our enable.sh ? Anything globally installed would still only be installed to the Flatpak it was run from.

**Comment by Lctrs** [comment]
Yes.

**Comment by p1u3o** [comment]
See https://github.com/flathub/org.freedesktop.Sdk.Extension.php73/pull/16

**Pull request closed without merging**
